<a href="https://colab.research.google.com/github/chaitra0312/tech/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Arthimtic Operations

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,5],[6,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 8 10  8]
 [10  7  9]]
[[-6 -6 -2]
 [-2  3  3]]
[[ 7 16 15]
 [24 10 18]]
[[0.14285714 0.25       0.6       ]
 [0.66666667 2.5        2.        ]]


#Mean And Standard Deviation

In [ ]:
a=np.array([1,2,3])
print(np.mean(a))
print(np.std(a))

2.0
0.816496580927726


# NumPy array of integers from 10 to 50 with a step size of 5

In [ ]:
a=np.arange(10,51,5)
print(a)


[10 15 20 25 30 35 40 45 50]


#Reshape the array into a 2x4 matrix.

In [ ]:
a=np.array([[1,2,3,5],[4,5,6,8]])
b=a.reshape(2,4)
print(b)

[[1 2 3 5]
 [4 5 6 8]]


#sub-matrix containing the last two rows and first two columns.

In [ ]:
 a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:,:2])

[[4 5]
 [7 8]]


#Replace all elements greater than 4 with 0.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[a>4]=0
print(a)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


 # Create two 1D arrays

In [ ]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
 print(a+b)
 print(a*b)
 print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


# Mean of each column

In [7]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[7,4,5,3]])
print(np.mean(a,axis=0))

[5.5  3.25 4.25 4.5 ]


# Maximum value of the entire array.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[7,4,5,3]])
print(np.max(a))

9


# Sum of all elements.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[7,4,5,3]])
print(np.sum(a))

70


# Add 10 to each element and multiply the result by 2.

In [ ]:
 a = np.array([1, 2, 3, 4])
 print(2*(a+10))


[22 24 26 28]


# Extract the second "layer"  in the first dimension.

In [ ]:
a=np.random.randint(1,101,size=(3,4,5))
second_layer=a[1]
print(second_layer)

[[83 64 74 69 88]
 [38 57 80 21 98]
 [ 9 51 97 91 64]
 [18 44 86 70 59]]


# Extract the first two rows and the last three columns from each "layer."


In [ ]:
a=np.random.randint(1,101,size=(3,4,5))
print(a[:,:2,-3:])

[[[99 97 70]
  [80  8 99]]

 [[74 58  6]
  [58 71 64]]

 [[98 76 74]
  [65 40 47]]]


#Replace all elements divisible by 3 with -1.

In [ ]:
a=np.random.randint(1,101,size=(3,4,5))
a[a%3==0]=-1
print(a)


[[[ -1  -1  -1  31  -1]
  [ 31  -1  -1  -1  14]
  [ 77  -1  14  13  71]
  [ -1  -1  53  -1  74]]

 [[ 73  65  61  70  -1]
  [ 98  31  32  37  50]
  [ 86  91  77  25  86]
  [  8  26  11  37  -1]]

 [[100  77  -1  -1   4]
  [ 19 100  -1  38  43]
  [ -1  -1  -1  -1  82]
  [ -1  13  -1  80  -1]]]


#Subtract the mean of each row from its respective elements

In [4]:
a=np.random.randint(1,21,size=(3,3))
b=np.mean(a,axis=1,keepdims=True)
print(a-b)


[[-6.          6.          0.        ]
 [ 4.33333333 -3.66666667 -0.66666667]
 [-3.          5.         -2.        ]]


# Create a new array by squaring all the elements in arr.

In [ ]:
a=np.random.randint(1,21,size=(3,3))
b=a**2
print(b)

[[144  16  64]
 [ 36 400 361]
 [361   9  81]]


# Find the indices of the top 3 maximum values in the entire array.

In [6]:
import numpy as np
a=np.random.randint(1,21,size=(3,3))
b=np.argsort(a.ravel())[-3:]
print(b)

[1 0 3]
